title: Sastu Insights
markdown: kramdown

# for atom feed
author:
  name: Sascha Stumpler
  email: sastu@sastu-insights.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]